- README.markdown
- tasks/windows/windows.rake
- test/test-installer.ps1
- wix/puppet.wxs
Puppet.msi and PuppetEnterprise.msi are now named puppet-agent.msi.
Work for removing the branding branching logic is not included here so if anything looks weird, it will be cleaned up with [PUP-3843](https://tickets.puppetlabs.com/browse/PUP-3843).
> (PUP-3844) Rename MSI to puppet-agent.msi

- conf/windows/stage/bin/environment.bat.erb
- foss-4.0-x64.yaml
- foss-4.0-x86.yaml
- tasks/windows/windows.rake
- wix/puppet.wxs
Add MCollective to be installed as part of the puppet agent
installer MSI. Previously MCO would only be installed if we were
building PuppetEnterprise.MSI. This removes the limitation and
additionally does the following:
- renames service from `pe-mcollective` to `mcollective`
- sets the intial account/password structure to the same as Puppet
which still defaults to `LocalSystem` and Empty password.
> (PUP-3842) Puppet should install MCO on FOSS

- README.markdown
- tasks/windows/windows.rake
- wix/include/puppet.wxi
- wix/puppet.wxs
This removes PE specific branding. It does make the observation that
version is now preferred to the same way that PE formerly did it where
you pass in `PE_VERSION_STRING`. However that has been renamed to
`AGENT_VERSION_STRING` to more accurately reflect what it is used for.
This is still waiting on what happens with `puppet.conf` `graph`
setting in PE.
This depends on the work that went into https://github.com/puppetlabs/puppet_for_the_win/pull/83 and should be evaluated AFTER it.
> (PUP-3843) Remove branding

- tasks/windows/windows.rake
Track versions of components in the MSI and install so that folks can
see exactly what went into the package. Create the file at
stagedir/misc just before heating the components so it gets baked into
the MSI and subsequently installed in
`INSTALLDIR/Puppet/misc/versions.txt`.
> (PUP-3845) Track versions of components

- tasks/windows/windows.rake
This pull request adds in updates that are needed to build the puppet-agent msi on a vmpooler image. We are no longer using the puppetwinbuilder tarball to provide the necessary packages. Those are instead installed via chocolatey. Because of that, there are a few differences in how we invoke commands.
> (maint) puppet agent updates

- conf/windows/stage/bin/environment.bat
We need to make sure this is available so that cfacter can load custom
facts, etc.
> (maint) Add the cfacter libdir to the ruby path

- tasks/windows/windows.rake
- wix/include/puppet.wxi
- Git has some interesting behavior when using `git describe` when the
current HEAD commit is a tag.  For instance, against the
puppet-win32-ruby repository and git version 1.7.8.msysgit.0, the
following behavior is observed, when performing a describe against
93d40ef (which is tagged as 2.1.5.0-x86):
> git describe
> 2.1.5.0-x86
> git describe --long
> 2.1.5.0-x86-0-g93d40ef
> (maint) use git describe --long when tag is HEAD

- tasks/windows/windows.rake
- Previously, the 4th number in the MCO version was used to indicate
changes beyond the FOSS tag in the PE fork.  With the AIO model, and
MCO included always, this becomes unnecessary
> (maint) MCO no longer needs 4th version field

- tasks/windows/windows.rake
- Previously, for extracted zips, such as CFacter, the versions.txt
included a `git describe --long` for the directory.  This would
actually traverse to a parent directory until it found one, in this
case the puppet_for_the_win repository itself.  As a result, the
versions.txt would contain the version of the puppet_for_the_win
repo, instead of the actual dependency.
For CFacter, a VERSION file was added as part of:
https://github.com/puppetlabs/cfacter/commit/26654b3
When the current download directory has a .git folder, indicating a
Git repo, then use `git describe --long` as we always have.
Otherwise, read the contents of the `VERSION` file
> (PUP-4006) Non-Git dependencies use VERSION file

- tasks/windows/windows.rake
- Git clones of large repositories are failing in more resource
constrained environments (such as the VMPooler instances that the
new AIO pipeline is using).  This has resulted in errors like
```
Resolving deltas:  46% (3744/8085)
error: index-pack died of signal 11
fatal: index-pack failed
rake aborted!
```
To address this issue, configure Git prior to cloning to adjust two
key settings:
The maximum size of memory that is consumed by each thread in
git-pack-objects[1] for pack window memory when no limit is given on
the command line. The value can be suffixed with "k", "m", or "g".
When left unconfigured (or set explicitly to 0), there will be no limit.
The maximum size of a pack. This setting only affects packing to a
file when repacking, i.e. the git:// protocol is unaffected. It can …
> (QENG-1892) Configure git clone with less memory

- tasks/windows/windows.rake
- Based on how the new AIO pipeline is invoking the Rake tasks, it was
determined that builds were using two different sets of tools.  This
commit simply logs what the current environment variables are (which
is useful for diagnosing PATH issues), and it also outputs tool
versions for the commonly used tools in the Rake tasks.
Unfortunately, candle, light and heat don't have --version or similar
switches.
> (RE-4056) Log environment variables / tools

- wix/puppet.wxs
Create the code directory and copy the default `hiera.yaml` file into
that directory. Also create the `hieradata` directory as a subfolder of
code.
Without these changes, pathing will not match with AIO on different
platforms.
> (PUP-4034) AIO - CodeDir / Hiera Changes

- tasks/windows/windows.rake
MCollective (from 2.8.1 onwards) maintains its version number in-tree rather
than storing @DEVELOPMENT_VERSION@.  Here we remove the windows:version task
as it is now uneccesary and will error when not able to make a change to
mcollective/lib/mcollective.rb
To be merged concurrently with https://github.com/puppetlabs/marionette-collective/pull/300
> MCO-617 Remove windows:version task

- wix/puppet.wxs
In order to support the puppet-agent run in a masterless setting, we
must provide these directories via the puppet agent installation, rather
than the puppet master installation.
> (PUP-4067) Add package manifest and module dirs

- conf/windows/stage/bin/environment.bat.erb
- tasks/windows/windows.rake
- wix/puppet.wxs
This is a cherry-pick of 2 commits with fixes related to the Marionette Collective 2.8.x release to the stable branch. One related to moving the plugins into the lib dir, and the other updating the version handling for the Marionette Collective packaging
> (maint)(packaging) Cherry-pick fixes for mcollective 2.8 release to stable

- conf/windows/stage/bin/mco.bat
- tasks/windows/windows.rake
Drop the use of the mco.bat from the marionette-collective repo
and instead prefer the use of an mco.bat included in PFW. This is
similar to how other bat files are included, e.g. puppet.bat and
facter.bat.
Also inlucde an environment variable for mcollectived.
This reverts changes introduced with https://github.com/puppetlabs/puppet_for_the_win/commit/07ea56edf9cbf96ffb920e35d9629d79cab339e5
> (MCO-625) Add mco.bat / required environment vars

- conf/windows/stage/bin/environment.bat
- Facter will look for environment variables that begin with FACTER_
and will automatically create facts out of them.  Inside of the
environment.bat file called prior to the Puppet command line
wrappers (puppet.bat, facter.bat, hiera.bat, etc) the temporary
variable FACTER_DIR was used to set up the PATH.
This had the interesting side effect of producing the DIR fact,
which was totally unintended and unspecified.
Simply rename this temp variable so that this doesn't happen.
> (maint) Remove accidental Facter 'dir' fact

- tasks/windows/windows.rake
Ensure that the appveyor.yml file doesn't get included with the
MSI.
> (maint) Remove AppVeyor file from MSI

- wix/PuppetForTheWin.wixproj
- wix/localization/puppet_en-us.wxl
- wix/ui/PuppetWarningDlg.wxs
- wix/ui/PuppetWelcomeDlg.wxs
- wix/ui/WixUI_PuppetInstallDir.wxs
- Introduce a new dialog into the UI sequence that shows after the
Welcome Dialog on Windows 2003 only.  It displays a link to more
information on the upgrade path for Puppet from Windows 2003.
- The dialog is dynamically injected into *only* the new install and
patch UI sequences and not maintenance, based on the VersionNT
property < 600.
- We are able to use only the VersionNT (and not VersionNT64) property
in this situation, because the installation is already blocked for
the x64 installer on Windows 2003.
- Note that there is nothing written to the installation log warning
about 2003.  It appeared that a custom action was the only solution,
and we're trying to avoid custom actions.
- The previous attempt at providing this functionality in 32e1aeb,
though simpler in code change terms, …
> (PUP-4631) Windows 2003 Deprecation Dialog

- tasks/windows/windows.rake
- wix/puppet.wxs
Currently, the Vanagon AIO package adds a VERSION file containing the
puppet-agent version string to the install directory.
This adds a corresponding file to the windows packages.
> (RE-5011) Add a puppet-agent VERSION file to the Windows package

- conf/windows/stage/bin/environment.bat
We want to ensure OpenSSL has secure settings, and the defaults are not
guarenteed to give us that. This commit updates SSL_CERT_FILE and
SSL_CERT_DIR to make sure we have safe locations set for both.
> (RE-5539) Set SSL environment variables for windows processes

- conf/windows/stage/bin/environment.bat
Prior to this change, we were using %WINDIR% to define where our SSL
variables were set. This, however, is an insecure way of doing it.
%WINDIR% has three attack vectors associated with it, whereas
%SYSTEMROOT% only has one. The one attack vector for %SYSTEMROOT% is by
far more difficult to exploit. Because of this, we want to default  to
%SYSTEMROOT% rather than %WINDIR%. In a generic setup, %WINDIR% defaults
to %SYSTEMROOT%.
WinDir has three attack vectors:
* Change the WinDir environment variable system wide.
* Overload any environment variable over MAX_PATH (2048 chars I believe
for env vars) and none of them (aside from built-in) work (PATH tends to
hit this limit sometimes).
* Change the WinDir environment variable in-process e.g. SET
WinDir=C:\bad.
SystemRoot has this attack …
> (RE-5539) Update SSL settings to secure default

- wix/puppet.wxs
Windows Server 2003 is no longer supported.
> (PUP-5064) Block Windows Server 2003 Install

- wix/puppet.wxs
Change the behaviour from auto-restart to exit so that the pxp-agent service does not restart on error exit.
> (PA-64) Set pxp-agent to exit on error

- wix/filters/filters.xslt
Added WIX xslt filter that ignores test binaries when building the MSI.
While this could get verbose, we can eventually split the xslt files
among the different products (i.e. one for puppet, one for facter, etc)
> (PA-68) Filter test binaries from MSI

- wix/filters/filters.xslt
Use a WiX xslt filter to ignore the following files:
lth_cat.exe
libfacter_test.exe
libtest.so
libtest1.so
cpp-pcp-client-unittests.exe
pxp-agent-unittests.exe
The first attempt at this removed them from the staging directories
inside ther rake task for building the agent itself. This was decided to
be too heavy handed, as end users may want the test assemblies in
downstream CI pipelines.
The second attempt used WiX filters to ignore the specified files when generating
WiX fragment files from the staging directory. This was a better
approach in that it left the files for anyone who needed them, and
removed them on the packaging step where they were not wanted. However
the filters turned out to be too greedy, and removed hundreds of files
from the MSI.
The third attempt uses a stricter …
> (PA-68) Filter test assemblies for Puppet MSI

- wix/puppet.wxs
As of Puppet 4.4.0, setting the pluginsync option by CLI
or config is deprecated and will log a deprecation warning,
as that behavior will eventually be managed based on whether or not
we are using a cached catalog.
While the setting is deprecated, it still defaults to true,
so removing this setting in puppet.conf will not cause a
change in behavior.
> (PUP-5933) Don't set pluginsync in puppet.conf

- wix/puppet.wxs
In `#20281` (167999a13afd622b0bc823650efbe303106b5ad0), we made a
change to allow overriding the current puppet.conf settings. This
came out in Puppet 3.4.0. This allowed being able to pass updated
settings to the installer and having them persist to the conf
file. Unfortunately, that also meant that any changes to the
puppet.conf file outside of install/upgrade time would be ignored
and overwritten by the remembered property values, which is
undesirable.
The conf file should also be looked at as an additional source of
remembered properties to allow keeping those settings when a user
is not overriding those settings during the install/upgrade. To do
this we need to copy the conf file to the Windows directory, read
the property values, and then remove the file from the Windows
directory …
> (PA-231) Keep Existing Puppet.Conf Settings

- wix/puppet.wxs
During upgrade scenarios, if the pluginsync value is found,
it should be removed from the puppet.conf file. This is follow up
for a7f45d46e018038b26dfd653465b6f581d27e1fe, which deprecated
setting the pluginsync value.
> (PA-225) Remove pluginsync setting from conf

- wix/puppet.wxs
In the current windows puppet setup, when installing the agent, the MSI will
update the puppet.conf file with environment=production by default. this will
break the workflow described in
https://docs.puppet.com/pe/latest/console_classes_groups_environment_override.html#workflow
so we need to update the MSI so it sets no default value.
> (PA-286) remove default environment setting in puppet.conf

- LICENSE
- README.markdown
- Rakefile
- tasks/windows/windows.rake
- wix/include/puppet.wxi
- wix/localization/puppet_en-us.wxl
- wix/puppet.wxs
As part of the brand rename, 'puppetlabs.com' has become 'puppet.com'.
This PR changes all instances to the correct name.
Based on #140
> (PA-285) Brand Name Change
